/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

/**
 *
 * @author fabri
 */
public class Laberinto extends javax.swing.JFrame {

    /**
     * Creates new form Laberinto
     */
    public Laberinto() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pos3 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        pos12 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos11 = new javax.swing.JLabel();
        pos4 = new javax.swing.JLabel();
        pos1 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        pos13 = new javax.swing.JLabel();
        pos17 = new javax.swing.JLabel();
        pos14 = new javax.swing.JLabel();
        pos15 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos16 = new javax.swing.JLabel();
        pos18 = new javax.swing.JLabel();
        pos19 = new javax.swing.JLabel();
        jLaberinto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        focoLeft = new javax.swing.JPanel();
        focoUP = new javax.swing.JPanel();
        focoRicht = new javax.swing.JPanel();
        focoDown = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        pos3.setText(" ");
        jPanel1.add(pos3);
        pos3.setBounds(180, 310, 50, 50);

        pos2.setText(" ");
        jPanel1.add(pos2);
        pos2.setBounds(130, 310, 50, 50);

        pos6.setText(" ");
        jPanel1.add(pos6);
        pos6.setBounds(130, 100, 50, 50);

        pos7.setText(" ");
        jPanel1.add(pos7);
        pos7.setBounds(240, 100, 50, 50);

        pos9.setText(" ");
        jPanel1.add(pos9);
        pos9.setBounds(230, 360, 50, 50);

        pos12.setText(" ");
        jPanel1.add(pos12);
        pos12.setBounds(440, 310, 50, 50);

        pos5.setText(" ");
        jPanel1.add(pos5);
        pos5.setBounds(130, 210, 50, 50);

        pos11.setText(" ");
        jPanel1.add(pos11);
        pos11.setBounds(340, 310, 50, 50);

        pos4.setText(" ");
        jPanel1.add(pos4);
        pos4.setBounds(180, 210, 50, 50);

        pos1.setText(" ");
        jPanel1.add(pos1);
        pos1.setBounds(130, 260, 50, 50);

        pos10.setText(" ");
        jPanel1.add(pos10);
        pos10.setBounds(340, 360, 50, 50);

        pos13.setText(" ");
        jPanel1.add(pos13);
        pos13.setBounds(440, 360, 50, 50);

        pos17.setText(" ");
        jPanel1.add(pos17);
        pos17.setBounds(440, 200, 50, 50);

        pos14.setText(" ");
        jPanel1.add(pos14);
        pos14.setBounds(490, 360, 50, 50);

        pos15.setText(" ");
        jPanel1.add(pos15);
        pos15.setBounds(490, 260, 50, 50);

        pos8.setText(" ");
        jPanel1.add(pos8);
        pos8.setBounds(240, 230, 50, 50);

        pos16.setText(" ");
        jPanel1.add(pos16);
        pos16.setBounds(440, 260, 50, 50);

        pos18.setText(" ");
        jPanel1.add(pos18);
        pos18.setBounds(490, 200, 50, 50);

        pos19.setText(" ");
        jPanel1.add(pos19);
        pos19.setBounds(570, 210, 50, 50);

        jLaberinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/laberinto.jpeg"))); // NOI18N
        jLaberinto.setText(" ");
        jPanel1.add(jLaberinto);
        jLaberinto.setBounds(120, 80, 460, 350);

        jPanel2.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 490, 80, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Fin");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 170, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estado");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 450, 80, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flechaAbajoRedimension.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 520, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arribaRedimesion.png"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 440, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flechaDerechaRedimension.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 480, 40, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flechaIzquierdaRedimension.png"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(550, 480, 40, 40);

        javax.swing.GroupLayout focoLeftLayout = new javax.swing.GroupLayout(focoLeft);
        focoLeft.setLayout(focoLeftLayout);
        focoLeftLayout.setHorizontalGroup(
            focoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        focoLeftLayout.setVerticalGroup(
            focoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(focoLeft);
        focoLeft.setBounds(680, 490, 20, 20);

        javax.swing.GroupLayout focoUPLayout = new javax.swing.GroupLayout(focoUP);
        focoUP.setLayout(focoUPLayout);
        focoUPLayout.setHorizontalGroup(
            focoUPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        focoUPLayout.setVerticalGroup(
            focoUPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(focoUP);
        focoUP.setBounds(600, 410, 20, 20);

        javax.swing.GroupLayout focoRichtLayout = new javax.swing.GroupLayout(focoRicht);
        focoRicht.setLayout(focoRichtLayout);
        focoRichtLayout.setHorizontalGroup(
            focoRichtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        focoRichtLayout.setVerticalGroup(
            focoRichtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(focoRicht);
        focoRicht.setBounds(520, 490, 20, 20);

        javax.swing.GroupLayout focoDownLayout = new javax.swing.GroupLayout(focoDown);
        focoDown.setLayout(focoDownLayout);
        focoDownLayout.setHorizontalGroup(
            focoDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        focoDownLayout.setVerticalGroup(
            focoDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(focoDown);
        focoDown.setBounds(600, 570, 20, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Resuelva el siguiente laberinto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 30, 312, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laberinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel focoDown;
    private javax.swing.JPanel focoLeft;
    private javax.swing.JPanel focoRicht;
    private javax.swing.JPanel focoUP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLaberinto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos11;
    private javax.swing.JLabel pos12;
    private javax.swing.JLabel pos13;
    private javax.swing.JLabel pos14;
    private javax.swing.JLabel pos15;
    private javax.swing.JLabel pos16;
    private javax.swing.JLabel pos17;
    private javax.swing.JLabel pos18;
    private javax.swing.JLabel pos19;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    // End of variables declaration//GEN-END:variables
}
